/**
 * es-area-api
 * Company related APIs of r2 SaaS System.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AreaVo } from './areaVo';

export class AreaTreeVo {
    'code'?: string;
    'parentCode'?: string;
    'id'?: number;
    'pId'?: number;
    'name'?: string;
    'idPath'?: string;
    'namePath'?: string;
    'children'?: Array<AreaTreeVo>;
    'keyPath'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "parentCode",
            "baseName": "parentCode",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "pId",
            "baseName": "pId",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "idPath",
            "baseName": "idPath",
            "type": "string"
        },
        {
            "name": "namePath",
            "baseName": "namePath",
            "type": "string"
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<AreaTreeVo>"
        },
        {
            "name": "keyPath",
            "baseName": "keyPath",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AreaTreeVo.attributeTypeMap;
    }
}

